#!/bin/sh
export TRANS_DIR=`dirname $0`
gawk \
-i "${TRANS_DIR}/metainfo.awk" \
-i "${TRANS_DIR}/include/Commons.awk" \
-i "${TRANS_DIR}/include/Utils.awk" \
-i "${TRANS_DIR}/include/LanguageData.awk" \
-i "${TRANS_DIR}/include/LanguageHelper.awk" \
-i "${TRANS_DIR}/include/Help.awk" \
-i "${TRANS_DIR}/include/Parser.awk" \
-i "${TRANS_DIR}/include/Theme.awk" \
-i "${TRANS_DIR}/include/Translate.awk" \
-i "${TRANS_DIR}/include/TranslatorInterface.awk" \
-i "${TRANS_DIR}/include/Translators/GoogleTranslate.awk" \
-i "${TRANS_DIR}/include/Translators/BingTranslator.awk" \
-i "${TRANS_DIR}/include/Translators/YandexTranslate.awk" \
-i "${TRANS_DIR}/include/Translators/Apertium.awk" \
-i "${TRANS_DIR}/include/Translators/SpellChecker.awk" \
-i "${TRANS_DIR}/include/Translators/Auto.awk" \
-i "${TRANS_DIR}/include/Script.awk" \
-i "${TRANS_DIR}/include/REPL.awk" \
-f "${TRANS_DIR}/include/Main.awk" -- "$@"
